### ISSUE TITLE
bug? truncated line of markdown in SVG output

### ISSUE THREAD

**Issue by TSSlade** [terrastruct/d2#644] opened 2023-01-11 08:02 UTC
The SVG below was generated via 

`$ d2 --sketch --pad 10 planning/process.d2`

following invocation of the `$d2 fmt` command. The last lines appear cut off when the SVG is viewed in Firefox Developer Edition:

<img width="857" alt="image" src="https://user-images.githubusercontent.com/3211478/211749712-cd83f8b5-4a59-44fd-a343-68e6760bd1b9.png">

Lines do NOT appear cut off when the SVG is viewed in Microsoft Edge:

<img width="809" alt="image" src="https://user-images.githubusercontent.com/3211478/211750626-500d152d-03f8-47a8-9841-0a4efe41dfa4.png">

**Comment by alixander** [comment] 2023-01-11 08:21
hmm, can you reproduce it in https://play.d2lang.com?

@TSSlade

**Comment by TSSlade** [comment] 2023-01-11 18:43
Looks like yes, but perhaps to a lesser extent?

![image](https://user-images.githubusercontent.com/3211478/211891071-e28c6f85-33d3-4da7-9774-83d80836c90b.png)

It's hard to see in this screenshot, but the last line under the left side is cut off at the descenders of the text. The right side remains cut off above the baseline.

**Comment by alixander** [comment] 2023-01-11 18:45
can you link it? @TSSlade

**Comment by TSSlade** [comment] 2023-01-11 18:50
For now, yeah. Would prefer to pull back down when you're done troubleshooting. [Here you go](https://play.d2lang.com/?script=lFhtb9y2sv4eIP9hUH-IvdhdN869vYBvUcON09RB4qa1U5-DovDOSqMVz1KkwiFX0Wny3w-G1Ntu09P2i18kcYaceeaZZ3gE30oo2VtXKbOBK5vBKbx1NiNmeIM1FNbB7c0l5OgRMqt1CvfjR48f1Y4WtdLWL9lmCjVwXZIjhsU3ML6r0XmVqRqNB63Y8zn89vgRwJC5c8htY-RRF8dz-HL55eNHn_Z8dKtuk6fb5Kl7CCCgUDk5FIN8Dh-rPL0AOIJro7ws-hm1yjHtPr2bze6Qt_GMr94BeyyK2Qygf31DHzx4VRGgBwTOSmv1HGSJJ8xKcgzKgC9pWLJxmBODLUAZL1v05_2rb-CLe9k15BZaG4BrMjmw2hhVqEzCE13FdZh5SUejfAk12VrTxRe9nf7385QMKJytoESTF0HD8VeL_7s4GbcXXyJDhabtDsDL0ca3yCpDrVtgoq249FaCWShXgXVAGtfWoScItTVwqZE9KveEYyrBFr2hBWRlcFk5_q_J5GJw42yoeXzeWLc9TTtJDz_Kr0_y4-0EKq8nUPmT_L62zaJEsxFvhQvKA5ocENbK5U94QS3BTlEzLDiC-7Idooi1D06W0gfFMeoVeYxwPwX03ql18MSAaxsEBRu1I9MHeIykdfDi6h1wy54qwMxbB43SGmpsIVc7lZPJI1ykjEKtCRps-Xy08HQJLwyuNTEEljxEaFJDDt4H4nhyAZbATZnCukriNCw_ZgtaqtYR19bkZDwU6NUm0En_zdmhC2Uy6-qUYbYV9faHWHTnGbywdyHzwREcZzqwJwndHEpFDl1WKuI5kM-WJ4JjCzY4KYm6TEAczIgPGzyTX_aPni3hDbZQkq5lc7izKoe1VlIjtfUMTUkG6uA4yMbE8uSk4waxqrV8sG5hS1TLn2KuQRdPZ3fkFpKtSIQLR7UjJuMp75A6mlImejlgvqXQ0gRJ6Pt_rwt4eKWKYP5N8E5TQw9wPJu9ejebnSRuAdSOMG-hxB2BsxK-lNK-XAffguCN7NVUcryaHFtjSM9BLMRCLS1TxJPJhW5rdOmx2jtCor7TeO6YIUnqkMTGBp3DmmBHroX3QWXbaC922E3pC-sadPmEMe77RU1krJKgsFrbRuyqAmrLrNaazieovsGKJgh8W1pDcBOqNblJ8n-ymuC4i8Qc7l_80CGp_-Z_lnAVfCuhlDzAsSoAd6i0APrkkB2vC6H0EuuaTIR6jDnmlTJKTueVpIAy63IGX6IfYzHYECwKqSqT0MIeTRd76lLyhIWbvDSKYw5ZKVwbgSqfDIZevUu0viMTt-4ETblUgOwsekdHOI-rcilG-eNz8BYCFlYik5NwXFRCsQRT1TV76VlbX3ZAiSiW1A6mmhI97UgqQb0PBNdXcApbajsDmrwUToVeTpU5yzwxxeR5uc_fqV_Hnm-wosWGjBC2dbzUqlJSYZzZmuDrBaTPIia1jnrhs-syW9WOSjKsdtQ1g32R8Bkd8Zf3MbidsPywt7-ylSOI6vAcStv8kX6ZaJfuuENT6xb_kB6nZ1jXzmJW7re4I3grlXm2eNb38KnCWMK1AambQaFEr_B0cQa5KgpyAqEHORGMJ3oYinpswAeHPtypFDK8HF73RPi6i-qtRHVY8wdnkai9-CAkTfAjj0-fLuG-FK1SWbMRfeQS5-ImEPeSyQdnpGIqG8WHJxO1G-Y7ldHFvjGRTo1Y7NZO1uSKs8AMvzxEP6JIHn7tlVxmg-PYKmA0iAasy5VB10JDtL043LjUb2JDp2Kj__w54oYOdjNxwyRtWBSubi_GPiOytyLYoVNJAEGFrfRuHXKaLF9ABHjPUL1G8RYejAQtbhENFMJ9kmt-iPGL2ElswzQH66Ymf3h3d3t99UICkuB1OgSt1pjRPKnUPwn1ZJfD8t9HfBrmX36TQM-hssaXn37dC8cRXAmdPR-aMtxJUUy3vbo2i0TRq8MOLg4T0-fSiXYKwUsP8SILuELn69iiJns-vkOzEa1D8o1oaetTaK0-aKKE3J4sp4svNVsoZK23EJigxprcaU0mUzpyspeO8a_AHkSJuJ79g_Z7kYuSCuGltRtN8J1NGl10m5e-voQ7af6KwVgPJbp8Lv2AS9mfeeKT9hEi0yqTJqNG9SUhu4_nkJ5YVTKa5DaKBYEeV6j1gjPUAqskDSVfsHJUWU8rOP5ZYWUXuRN5fHGyVzwdD0DfIHPSakeuxykLrfzIMRG3b27lTCKr-LKu9-J4LVoHVE4oMXfS5EjiKn2wwTa2UqfQbILeb6Eslad8Kf02w8BRqwwKuhPJe65uLKyd0lrJB-KRIY5uLfm972KBCCjqCKxKNJMgwdskREnGxrBmwdZE5p19SEVzFskkTgVr8g2RObAe635Dfoyz5NrmMpDePZ2n5MT3aoT79JP_T8UdAbYhz0l5R-zK-7Pe2cf0x6f06_lnmt1_ZfSvn6MAzFFFIus6-nHVN1N8vcTkt58dpyQ1DNK__LZKNLOaw0q05-rTr0t4K0yTtG1cvKZC2Az75Xs4_l6U3oGAMtbTfCS72Att8igG55FcbWBQnqrPz-8d2X_n6H0gk7XykWg_zLzsOkel27hpom36K45jRfreryKHjabOlnAl2o9a4JpwmxDhS5ke46jZsW1kSvahKC5g9U_i0xu7mtp5toS7b6_g-G1S3u3IB6DVluDhXnLfXTjgVqC5-sdq3nN1mhC6csms2ZHj2GTm-0i0TlbIdi9O_iYVv1Zb0rE81wTr4HIyEbfHhQtJiot-ZW2bk5ihg9SpAph0sei1OznKIVcb5aVN7mV-iAF9qBN4TxtkTyLik_vI-NYkCr6Yrn2D7ZqAGyIfB07hURkNZWgit-e9a3kIwiQytTgKHKcQqJ2QdBjgPYlhbLgQe2beA3j_qPO-GUyPL_lPhAUIRmWk28UwwMlsLAMhl0R-0iL3y7m7A9yr2puXnDRLVJPxtoGpWkfG6usz7ThdIXX3HiNt9oaGCbqjc-Xg6SKnjSMCQ162L42JmKI_4pqSwBksBI4JimMT5kKlZiPBtS7ugo1t1rH99KO9p6xMM4vApTeTLoZDNuif3vu-ypVfl4Pg_2s3TG-UUVWo4DIiXDINP3WdZToXx4k43dscJLGHtSaZ37ogxmpJtZ7i1rPJeAvAw0DdzahKa2AvPyntI93jxGsR6k79wYPGlpwE7_DyYnJfdMkc4qUvqY6XG9xRvBsZQr5GljGzo_3lpK3PZv21au1sbRn1bDYd-p-nszxhWBVB64il1eQWYPI-qS0TLwRWaayvo0SZzvXPlrB6nibtVYTkqTLQlCo1t2mst8Y2nIh0PCwtN8t5d0c537-bnA9j0-F1w2SPzmoROWIGhjuK7-_mUCN76-awRrMldyqW5VWaxqfRmtyNzGb98__9W_0kSuFJa4kSW_rK1NFL8j6djShvJ76-WsJrQV_vo-s32N8uiVNvc2xX81XstOI4-pJV_T8dcY3PhrY2jpFHv2OcI2GAQcSkJx_jiPyfAAAA__8%3D&).

**Comment by alixander** [comment] 2023-01-11 18:54
ah looks like firefox is rendering bold differently, leading to mismeasurements. thanks so much @TSSlade , feel free to remove the link, will be fixed in next release

**Closed** 2023-01-11 19:07 UTC
