### ISSUE TITLE
how to change text sizes?

### ISSUE THREAD

**Issue by lucasjinreal** [terrastruct/d2#429] opened 2022-12-12 03:39 UTC
When graph became big and complicated, the label are too small.

Also, how to make the graph have a limited width and auto-gen layout? Since I want using this graph insert to PPT, but PPT can not insert too wide pictures.

**Comment by alixander** [comment] 2022-12-12 03:53
you can set `font-size`, but there's no setting to change the global. this is a TODO.

You won't be able to constrain width/height, but you can set direction. https://d2lang.com/tour/layouts#direction
this currently only works for top-level though. in the next release for the TALA layout engine, you will be able to set direction per-container, which should hopefully allow you to limit how horizontal it grows

**Comment by jinfagang** [comment] 2022-12-12 05:09
@alixander Oh, am using the default rendering engine, how does it support orientation per group? 

Also, when will all these 2 features be support?

**Comment by oderwat** [comment] 2023-01-21 14:15
I just came here for the same thing. 

Even on https://text-to-diagram.com/ it is clear (for me and the team) that D2 is inferior in readability with most of the examples.

I think that is mostly because of the font to padding ratio is badly chosen. With the font being too small and the padding being much too large. 

I also think that the text for sequence diagram interactions in between the arrow is a bad choice and makes it not looking like a sequence diagram at all. Where are my interactions? I only see a garbled mess of text and something that may be a line with an arrow?

Here, a simple example. Just imagine the font being bigger and the padding and spacing more compact. And the interactions not being "garbled" with the text, but having the text on top, which also give more room for them to be bigger. Dashed lines, are also harder to notice when the line itself is interrupted.

P.S.: Making an interaction a dashed line could be easier in the DSL than adding styling (e.g. using `-->` instead of `->`). You do not usually want many different styles for your dashed interactions, so it would be much more usable to define that style (or just have a sensitive default).

On the first sight placing the image inside the comment here it is "okay" on "full width" because it has only few participants. I scaled it to 50%, and it immediately becomes very hard to read. Also, it is much too tall. There is so much emptiness in this diagram.
 
<img width=50% height=50% src="https://user-images.githubusercontent.com/719156/213870247-e617cba9-661e-44a7-876e-6e7ca33b784c.png">

```d2
shape: sequence_diagram

k: D2 Sequence Diagram
y: You
s: support@terrastruct.dom

y -> k.a: Launch the application {
  stroke-dash: 4
}
k.a -> y: Welcome to D2
k.a -> y: I really hope you enjoy\nusing it
y."Note to self:\nI need to order some pizza"
loop: {
  y -> y: do some work
  y -> s.a: this is not so great 😢
}
```

You write about the design choices and want to go for readability of the DSL. I think that should be even more emphasized for what it produces because this will be ingested by far more people. To me, the diagram looks like something a designer would do, and that is (sadly) very frequently not what a consumer wants :)

P.S.: We currently have to decide between using Plan UML and D2 and I can't make a point for D2 because the team cannot read the diagrams as easily. Normally, I would try to get a PR out that fixes what, I think, should change, but we do not have the time right now :(

**Comment by alixander** [comment] 2023-01-21 18:01
@oderwat I appreciate the detailed writeup. We've heard the text sizing and excessive padding from multiple sources now, and will followup a new version with better defaults. We're actively working on this -- in progress right now is making the labels position more accurately per shape, and then we'll just change the constants (https://github.com/terrastruct/d2/pull/702). 

We'll get the next version out by eow.

the excess height is something i hadn't heard before for sequence diagrams, but I'll play around with it too and post here

**Comment by oderwat** [comment] 2023-01-22 16:42
While at it, I think the whole system would also benefit if one could set the default base font-size and use percentages for fonts in style definitions.

**Comment by alixander** [comment] 2023-01-22 18:54
this'll be done with globs. (https://github.com/terrastruct/d2/issues/103)

`*.style.font-size: 55`

**Comment by oderwat** [comment] 2023-01-22 18:58
That is nice, but I meant that I want to specify the size of a text relative like "100%", "120%", "80%" to make it easier to scale the whole thing for different usage scenarios. So, you just need to modify the base font-size and the remaining text will adapt to it. Otherwise, you need to go through the whole document and change the sizes.

**Comment by alixander** [comment] 2023-01-22 19:04
thanks @oderwat , will continue that thread here: https://github.com/terrastruct/d2/issues/709

**Comment by alixander** [comment] 2023-02-19 05:43
D2 0.2 makes things more compact. though the labels still do obscure a bit too much of the edge, the empty spacing issue is fixed:

<img width="410" alt="Screen Shot 2023-02-18 at 9 43 36 PM" src="https://user-images.githubusercontent.com/3120367/219930083-9191636d-20f2-4fc7-b316-0da3acd465ae.png">

https://play.d2lang.com/?script=TJK_SjRBEMTzfori8m-D44smEINNDsTEQIQDaXbb3XFnp8f5wzEnF_kSZr6ijyC7rnDpj67uKrpWrwZJ3or4Tp57y0PkmWgyaPd42DjajVeDJy2UDFIJQWO-zRIjpxxLl5teZ6KKfzeYGja44-K7EXkUcAjOdry8Fe8EXEU0-E8XmhpedNXgUVynsyAr2v0VPyAKO1cxahBULRD_qvXoS7J-gM1Um9295lWZxL2Yoz_Ai_QLWHuDtCwO9nzmHTnVYFYzdbvQ6-_ASeP0h9MSJI82wSZ4PWGIwhnfX58fdKGfAAAA__8%3D&

**Comment by kiriti999** [comment] 2023-08-31 17:55
I just started using D2 today after comparing with other diagram providers but if text size cannot be increased then what's the point?

**Comment by alixander** [comment] 2023-08-31 20:41
oh this can actually be closed. globs has been implemented:

https://play.d2lang.com/?script=Ks9ILClW0LVTKMlIBVEF-Zl5JVxcWlYK1VwKCmCL9ODBY6VgaspVywUIAAD__w%3D%3D&

<img width="1241" alt="Screen Shot 2023-08-31 at 1 41 11 PM" src="https://github.com/terrastruct/d2/assets/3120367/2eb9f775-b4da-4894-9024-2b0ec06d3a8a">

**Closed by alixander** 2023-08-31 20:41 UTC

**Comment by kiriti999** [comment] 2023-09-02 21:56
@alixander It only works on basic structures but not for nested structures. I am not sure if an architecture can be created only using basic boxes so whats the point?

![image](https://github.com/terrastruct/d2/assets/13074074/0d62b575-2671-4053-a546-4120e5d18284)

**Comment by alixander** [comment] 2023-09-03 10:45
@kiriti999 I'm happy to help but please show some effort and help yourself first through the extensive documentation available: https://d2lang.com/tour/globs/

If you're still confused after, make a new issue and I'll help.

To answer your question this time:

<img width="1248" alt="Screen Shot 2023-09-03 at 3 44 00 AM" src="https://github.com/terrastruct/d2/assets/3120367/6c31323c-c140-405a-a38a-b9ec2ef56ec7">


https://play.d2lang.com/?script=Ks9ILCm2UqjmUlAoyUiFMBQUCvIz80q4FBRquWq5uLS0IMJgW_XgYWWlYGzKVcsFCAAA__8%3D&

**Comment by kongdd** [comment] 2024-03-10 08:39
any idea how to change the font-size of the link text
```d2 
x -> y: hello world

**: {
  style.font-size: 55
}
```
![image](https://github.com/terrastruct/d2/assets/9815742/d6844a21-b0d7-46f3-94b9-356b3ea742fd)

**Comment by alixander** [comment] 2024-03-10 18:47
@kongdd 

```d2
(* -> *)[*]: {
  style.font-size: 55
}
```

**Comment by louisabraham** [comment] 2024-03-27 16:48
> @kongdd
> 
> ```d2
> (* -> *)[*]: {
>   style.font-size: 55
> }
> ```

this should definitely be added to the documentation

**Comment by pidgeon777** [comment] 2024-03-28 09:21
> > @kongdd
> > ```d2
> > (* -> *)[*]: {
> >   style.font-size: 55
> > }
> > ```
> 
> this should definitely be added to the documentation

I agree 👍.

**Comment by qd3v** [comment] 2024-11-04 10:50
Few cents, my tests shows these work better (for imports `***` maybe used I guess):
```
**.style.font-size: 10
(** -> **)[*].style.font-size: 10
```
I found another issue (0.6.7): this styling does not apply if any of ! `->` used: `--`, `<-`, `<->`.

---

In my case, lowering font-size didn't help...

I'm playing with D2 (Activity diagrams) all morning, I can see big potential, reusability and so on, but Puml gives **much** shorter diagrams. I added only few steps, and diagram does not fit into monitor already (I know I can rotate layout, but that won't help if I add 1 or 2 steps more). And the problem is not in steps amount, but in a way space is used: it's just wasted :( 
I'm getting huge square shape with tiny text with lots of space around it, and extremly long arrows... Changing layout engine didn't help.

All good, but padding ruins the readability and displaying/printing options.
Playing with size this way:

```
**: {
  # trying to reduce padding as much as possible
  &shape: hexagon
  width: 150
  height: 40
  # I was hopping that CSS-like approach works...
  # BTW, try to add this :) <---- !!!
  pad: 0
}
```
ruins the whole idea of autolayout. The above approach comes at the cost of fixed size and the need of re-styling elements selectively when needed.

Anyway, good work! 👍 Waiting for new D2 versions
