### ISSUE TITLE
FR: Add the ability to add connections to connections

### ISSUE THREAD

**Issue by MrPixelized** [terrastruct/d2#2073] opened 2024-08-26 07:16 UTC
For example: the data transfer from node A to C affects the data transfer from node D to C in the following way (arrow from the connection between A and C to the connection between D and C).

**Comment by alixander** [comment] 2024-08-26 14:21
dupe of https://github.com/terrastruct/d2/issues/423

**Closed by alixander** 2024-08-26 14:21 UTC
