### ISSUE TITLE
Labels overlapping when image is used

### ISSUE THREAD

**Issue by JulienFloris** [terrastruct/d2#468] opened 2022-12-19 19:21 UTC
Hello

Not sure if this issue is a duplicate with one of these issues;
- #126 
- #12 
- #414 

But labels overlap in this example below. Is there a existing fix for this, i could not find anything in the documentation?

![image](https://user-images.githubusercontent.com/20380255/208503045-e1a1b8c8-774c-4d04-898a-04973f228f71.png)

```d2
# Example Code
user: {
  shape: image
  icon: http://code.benco.io/icon-collection/azure-icons/Users.svg
}

user -> Azure.Traffic-Manager

Azure: {
  Traffic-Manager: {
    shape: image
    icon: http://code.benco.io/icon-collection/azure-icons/Traffic-Manager-Profiles.svg
  }

  West-Europa: {
    Public-Loadbalancer: {
      shape: image
      icon: http://code.benco.io/icon-collection/azure-icons/Load-Balancers.svg
    }
    RDG: {
      RDG01: {
        shape: image
        icon: http://code.benco.io/icon-collection/azure-icons/Virtual-Machine.svg
      }
      RDG02: {
        shape: image
        icon: http://code.benco.io/icon-collection/azure-icons/Virtual-Machine.svg
      }
    }
    Public-Loadbalancer -> RDG.RDG01: {
      label: 50% If Healty
    }
    Public-Loadbalancer -> RDG.RDG02: {
      label: 50% If Healty
    }
  }

  North-Europa: {
    Public-Loadbalancer: {
      shape: image
      icon: http://code.benco.io/icon-collection/azure-icons/Load-Balancers.svg
    }
    RDG: {
      RDG01: {
        shape: image
        icon: http://code.benco.io/icon-collection/azure-icons/Virtual-Machine.svg
      }
      RDG02: {
        shape: image
        icon: http://code.benco.io/icon-collection/azure-icons/Virtual-Machine.svg
      }
    }
    Public-Loadbalancer -> RDG.RDG01: {
      label: 50% If Healty
    }
    Public-Loadbalancer -> RDG.RDG02: {
      label: 50% If Healty
    }
  }

  Traffic-Manager -> West-Europa.Public-Loadbalancer: {
    Label: 90% Traffic
  }

  Traffic-Manager -> North-Europa.Public-Loadbalancer: {
    Label: 10% Traffic
  }
}
```

**Comment by alixander** [comment] 2022-12-19 19:23
Thank you @JulienFloris , can reproduce. This will be fixed this week. Sharing Playground link to track:

https://play.d2lang.com/?script=7JRPa_owGMfveRUP_PCYVIXfYT0MtiluoENkf86P8akGYiNJOvaHvveRZp3SOSm97OKl0KR8vh_yfJt_MH7F7U4T3JgVscKRTeGDAVT-KagtrokBhFNJYeP9Lk0SaVYklpRLI5RJwlY4Uh3nkOB7YYmHVZc8OrJOuJc1K1kFB34JV-ED8WAxy5TkM8xxTZaxajmGN_bi4g-nzlYNPJ9bkylNURSgZAzgmZzn4yJMuI6fF0utJJ8aXC1RYy73ZkfcOtsFPr_-CqidglV4LkaTfeZiNOkP9q9HJTprPCnrC9R8hnKjcvr2qE1i_PCv4svfRhIathhNRONwqt84hf_9HtxlcEuo_Vt70LAlqKrOvbF-c-7OuTsdutO4mgLn4CYSJ2o0jeyLfq-GnGAeVrQFdNCAluwzAAD__w%3D%3D&theme=105

**Comment by alixander** [comment] 2022-12-19 19:26
@gavin-ts can you look into bringing the label placement code to be usable for all layout engines?

**Comment by kamok** [comment] 2022-12-19 21:38
Just to clarify, this is adding relative positioning to a Shape label (as well as Container) right?

So you have the standard top, bottom, right, left of a Shape. But what about something like bottom right? How does that work? Is text align also coming? 

As complexity of increases, it would be good to get the classes feature in so we can style objects all at once. https://github.com/terrastruct/d2/issues/102 My d2 file is already getting bloated.

**Comment by alixander** [comment] 2022-12-19 21:46
we have code in our custom layout engine to place labels in a location where it avoids obstructions. So if you render with the TALA engine: 

https://play.d2lang.com/?script=7JRPa_owGMfveRUP_PCYVIXfYT0MtiluoENkf86P8akGYiNJOvaHvveRZp3SOSm97OKl0KR8vh_yfJt_MH7F7U4T3JgVscKRTeGDAVT-KagtrokBhFNJYeP9Lk0SaVYklpRLI5RJwlY4Uh3nkOB7YYmHVZc8OrJOuJc1K1kFB34JV-ED8WAxy5TkM8xxTZaxajmGN_bi4g-nzlYNPJ9bkylNURSgZAzgmZzn4yJMuI6fF0utJJ8aXC1RYy73ZkfcOtsFPr_-CqidglV4LkaTfeZiNOkP9q9HJTprPCnrC9R8hnKjcvr2qE1i_PCv4svfRhIathhNRONwqt84hf_9HtxlcEuo_Vt70LAlqKrOvbF-c-7OuTsdutO4mgLn4CYSJ2o0jeyLfq-GnGAeVrQFdNCAluwzAAD__w%3D%3D&theme=105&layout=tala

There are 21 positions to choose from for each node. E.g. outside top left, inside center right, etc.

This work is to bring this label obstruction avoidance to the other layout engines.

**Comment by kamok** [comment] 2022-12-19 22:11
I modified the sample with a longer label and it breaks the label detection due to overflow. I believe manual placement would solve this (let user dictate the least worse option). Unless your team gives us a firm constraint of  "we don't support labels exceeding x characters."

https://play.d2lang.com/?script=7JRPawIxEMXv-RQDxWN2Veiheyi0VWxBi0j_nMd1VgNxI0m29A_73cts3CpbKXah9OIlkEl478fMY85g-IrrjSa4MQsShSObwIcAqPgTUGtckgDgriSw8n6TxHFqFhTNKU9NpEzMT9xSHeYQ43thSXLVxY-OrIvcy1KUohIHeQlX_CF6sJhlKpUTzHFJVoiqHMwbb6H4jak1VUNeTq3JlKYAClAKAfBMzsthwROu7afFXKtUjg0u5qgxT8lKbXJWqEJS_zsA2hqVzeT11q0GZEQ-Z4PRznM2GHV7u-tBiNYYT8r6ArWcYLpSOX1x1CTBvv9f9uVR8-HszQajqNGp7ezOux24y-CWUPu3lqr9I1WrhN0b61eniJ0i9ncRayw61tnba9GxaRuHy0W3Uyv-YLAf69869BoOpfgMAAD__w%3D%3D&theme=105&layout=tala

**Comment by alixander** [comment] 2022-12-19 22:17
@kamok the detection does not guarantee no obstructions, it just chooses the place with least obstructions. Here the control lever would be to put a newline in middle of the long label.

The problem with manual placements is that as the diagram changes, the arrow that a previous manual placement was avoiding may have moved, and is now obstructing again.

**Comment by kamok** [comment] 2022-12-19 22:26
> The problem with manual placements is that as the diagram changes, the arrow that a previous manual placement was avoiding may have moved, and is now obstructing again.

Wouldn't this be the same for controlling the label length with a new line symbol? There seems to be a limit of length of labels here that needs to be set or else I'm going to be adding or removing `\n` every time someone changes the diagram.

**Comment by alixander** [comment] 2022-12-19 23:10
Actually, maybe the solution here is to just consider the labels for object dimensions in these layout engines. E.g.

<img width="320" alt="Screen Shot 2022-12-19 at 3 09 19 PM" src="https://user-images.githubusercontent.com/3120367/208545638-5bb53ee8-a1db-430c-91ae-99f52107ff83.png">

**Comment by gavin-ts** [comment] 2022-12-20 02:53
> Actually, maybe the solution here is to just consider the labels for object dimensions in these layout engines. E.g.
> 
> <img alt="Screen Shot 2022-12-19 at 3 09 19 PM" width="320" src="https://user-images.githubusercontent.com/3120367/208545638-5bb53ee8-a1db-430c-91ae-99f52107ff83.png">

This could work for images specifically (e.g. if we set the dimensions of the image shape as the combined bounding box), but if they were containers with labels it wouldn't work in dagre since it ignores the provided dimensions if it is a container. Another issue is connections to the shape would now go to the larger bounding box and if it is a shape we would have to undo this to get the actual shape dimensions before tracing to its border.

**Comment by alixander** [comment] 2022-12-20 03:03
@gavin-ts ohh that's fucking right, goddamnit dagre.

Okay, since we can't control that, why don't we make all labels on the bottom or top, and then use those dimensions for dagre/elk?

> Another issue is connections to the shape would now go to the larger bounding box

i think this is a feature not a bug. See discussion here: https://github.com/terrastruct/d2/discussions/216#discussioncomment-4240817

**Closed** 2022-12-20 07:44 UTC
