### ISSUE TITLE
grid distorts circle shape

### ISSUE THREAD

**Issue by alixander** [terrastruct/d2#1449] opened 2023-06-26 23:37 UTC
`grid` distorts circle shape

![Screen Shot 2023-06-26 at 4 37 04 PM](https://github.com/terrastruct/d2/assets/3120367/67d103c1-dbe2-4b6d-8d11-c4f389655072)

```d2
style.fill: transparent

grid-rows: 4
grid-columns: 4
rectangle.shape: rectangle
square.shape: square
page.shape: page
parallelogram.shape: parallelogram
document.shape: document
cylinder.shape: cylinder
queue.shape: queue
package.shape: package
step.shape: step
callout.shape: callout
stored_data.shape: stored_data
person.shape: person
diamond.shape: diamond
oval.shape: oval
circle.shape: circle
hexagon.shape: hexagon
cloud.shape: cloud
```

**Comment by gavin-ts** [comment] 2023-06-27 00:06
duplicate of #1405

**Closed by gavin-ts** 2023-06-27 00:06 UTC
